package azurerm

var (
	nodeTypes = map[string]struct{}{
		"azurerm_app_service":                       {},
		"azurerm_app_service_certificate":           {},
		"azurerm_app_service_environment":           {},
		"azurerm_app_service_plan":                  {},
		"azurerm_application_gateway":               {},
		"azurerm_bastion_host":                      {},
		"azurerm_batch_account":                     {},
		"azurerm_batch_application":                 {},
		"azurerm_batch_pool":                        {},
		"azurerm_cdn_endpoint":                      {},
		"azurerm_cdn_profile":                       {},
		"azurerm_container_group":                   {},
		"azurerm_container_registry":                {},
		"azurerm_cosmosdb_account":                  {},
		"azurerm_data_factory":                      {},
		"azurerm_dedicated_host":                    {},
		"azurerm_dedicated_host_group":              {},
		"azurerm_dns_zone":                          {},
		"azurerm_firewall":                          {},
		"azurerm_frontdoor":                         {},
		"azurerm_function_app":                      {},
		"azurerm_image":                             {},
		"azurerm_kubernetes_cluster":                {},
		"azurerm_kubernetes_cluster_node_pool":      {},
		"azurerm_lb":                                {},
		"azurerm_linux_virtual_machine":             {},
		"azurerm_mariadb_database":                  {},
		"azurerm_mariadb_server":                    {},
		"azurerm_mssql_database":                    {},
		"azurerm_mssql_elasticpool":                 {},
		"azurerm_mssql_server":                      {},
		"azurerm_mssql_virtual_machine":             {},
		"azurerm_mysql_database":                    {},
		"azurerm_mysql_server":                      {},
		"azurerm_nat_gateway":                       {},
		"azurerm_nat_gateway_public_ip_association": {},
		"azurerm_netapp_account":                    {},
		"azurerm_netapp_pool":                       {},
		"azurerm_netapp_volume":                     {},
		"azurerm_postgresql_database":               {},
		"azurerm_postgresql_server":                 {},
		"azurerm_private_dns_zone":                  {},
		"azurerm_private_endpoint":                  {},
		"azurerm_public_ip":                         {},
		"azurerm_redis_cache":                       {},
		"azurerm_sql_database":                      {},
		"azurerm_sql_server":                        {},
		"azurerm_storage_container":                 {},
		"azurerm_virtual_machine":                   {},
		"azurerm_virtual_network_gateway":           {},
		"azurerm_vpn_gateway":                       {},
		"azurerm_windows_virtual_machine":           {},
		"azurerm_virtual_network":                   {},
	}

	// edgeTypes map of all the supported Edges
	edgeTypes = map[string]struct{}{
		"azurerm_virtual_network_peering": {},
	}
)
